name: Build and Deploy Eleventy Site

on:
  push:
    branches:
      - main  # 배포할 브랜치

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # 필요에 따라 버전 변경

    - name: Install dependencies
      run: npm install

    - name: Build site with Eleventy
      run: npx @11ty/eleventy

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # Eleventy 기본 빌드 결과 폴더
        publish_branch: site
